config/routes.rb
PromiseApp::Application.routes.draw do
  devise_for :users

  
  root :to => 'resolutions#index'
  resources :users
  resources :resolutions
  resources :friendships, only: [:create,:destroy,:update]
  resources :comments, only: [:create, :destroy]
  resources :updates, only: [:create, :destroy]
  resources :likes, only: :create
  
  match 'unlike' => 'likes#unlike', as: :unlike
  match 'read/:count' => 'notifications#read', as: :read
  match 'profile' => 'users#profile'
  

end

app/views/layouts/_navigation_bar.html.erb
<% if user_signed_in?%>
<header class="nav">
	<div class="navbar clearfix">
		<ul class="left-menu">
			<li>
				<div><a href="<%= resolutions_url %>"><%= image_tag "transparentlogo.png", height: '12px',  class: 'logo'%></a>
				</div></li>
			<li>
				<div><a class="request-tab" href="#">
					<% requests = current_user.friend_requests %>
					friend requests 
					<% if requests.length > 0 %>
						<strong class="badge"><%= requests.length %></strong> 
					<% end %>
				</a></div>
				<ul class="nav-dropdown requests-list bubble clearfix">
					<% requests.each do |request| %>
						<li class="clearfix">
							<div class="request">
								<div class="name"><%= link_to(request[:friendname],user_url(request[:user_id])) %></div>
								<%= button_to "Accept", friendship_url(request[:id]), method: "put", remote:true, class:"new_friend" %>
							</div>
						</li>
					<% end %>
				</ul>
			</li>
			<li>
				<div>
				<% note_count = current_user.notifications_count %>
				<% if note_count > 0 %>
					<a class="notification-tab" data-remote="true" href="
						<%= read_url(note_count) %>">
				<% else %>
					<a class="notification-tab" href="#">
			  <% end %>
					notifications
					<% if note_count > 0 %>
						<strong class="badge"><%= note_count %></strong>
					<% end %>
				</a></div>
				<ul class="nav-dropdown notifications-list bubble clearfix">
					<% notifications = current_user.notifications.includes(:activity).reverse %>
					<% notifications.each do |note| %>
						<li>
							<div class="message">
								<%= link_to(note.message,user_url(note.activity.user_id)) %>
							</div>
						</li>
					<% end %>
				</ul>
			</li>
		</ul>
		
		<div class="search-bar">
			<input class="searchbar" value="TODO searchbar">
		</div>
		
		<ul class="right-menu">
			<li>
				<div><a href="#" class="home-tab">home</a></div>
				<ul class="nav-dropdown home-message bubble">
					<li>
						<div class="message">
							under construction
						</div>
					</li>
				</ul>
			</li>
			<li><div><%= link_to("profile", profile_url) %></div></li>
			<li><div><%= link_to("logout", destroy_user_session_url, method: :delete)%></div></li>
		</ul>
	</div>
</header>

<% end %>

<script>

$('.button_to').on("ajax:success", function(event){
	$(event.target).parent().parent().hide();
	var $badge = $('.badge');
	($badge.text() == 1) ? $badge.addClass('friended') : $badge.text($badge.text()-1)
});

$('.notification-tab').on("ajax:success", function(){
	$(this).find('.badge').hide();
});

$('.navbar > ul > li > div').hover(
	function () {
    $(this).addClass("swing animated");
  },
  function () {
    $(this).removeClass("swing animated");
  }
);

$(window).scroll(function() {
    $('.navbar').css('left', -$(this).scrollLeft() + "px");
});

</script>

app/views/layouts/_profile.html.erb
<div class="profile-container">
<section class="profile clearfix cut-out glow">
	<figure>
		<%= image_tag current_user.profile_photo.url(:big) %>
	</figure>
	<table class="user-info">
		<tr class="username">
			<td></td>
		</tr>
		<tr class="characteristic">
			<td></td>
			<td></td>
		</tr>
	</table>
</section>

app/views/layouts/_right_feed.html.erb
<aside class="feed-right glow">
	<h3>Friend Activity</h3>
	<ul>
		<div class="feed-right-scroll-container">
		<% current_user.feed.each do |friend_activity| %>
			<li>
				<figure><%= link_to(image_tag(friend_activity.activity.user.profile_photo.url(:thumb)),user_url(friend_activity.user_id)) %></figure>
				<h4><%= link_to(friend_activity.activity.user.username,user_url(friend_activity.activity.user_id)) %></h4>
				<header>
					<div class="news">
						<%= "made a new " %>
						<%= link_to(friend_activity.activity_type, resolution_url(friend_activity.activity_id)) if friend_activity.activity_type == "Resolution"%>
						<%= link_to(friend_activity.activity_type,
						resolution_url(friend_activity.activity.updateable_id)) if friend_activity.activity_type == "Update" %>
					</div>
				</header>
			</li>
		<% end %>
		</div>
	</ul>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Promisrs</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= csrf_meta_tags %>
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
	<%= javascript_include_tag "application" %>
</head>
<body>
	
	<%= render :partial => 'layouts/navigation_bar' %>
	
	<div class="errors">
		<div class="error-bar <%= 'center' unless current_user %>">
		<p class="notice"><%= notice %></p> 
		<p class="alert"><%= alert %></p>	
		</div>
	</div>
	
	<div class="content clearfix">
		<% if user_signed_in? %>	
			<%= render :partial => '/layouts/right_feed'%>
			<%= render :partial => '/layouts/profile'%>
		<% end %>
		<%= yield %>
	</div>
	
	<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
	<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	
</body>
<footer>
	<div class="footer-bar">
		<div class="logo">Promisrs &copy; 2013
		<% unless Time.now.year == 2013 %>
		- <%= Time.now.year %>
		<% end %></div>
	</div>
</footer>
</html>